<div class="space large"></div>
<div class="space large"></div>

<section class="padtop">
    <div class="content">

        <div class="row title-row">
            <div class="col-12">
                <h1>Your Links</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="frame" id="links">
                    <div class="frame__header"></div>
                    <div class="frame__body">
                        <table class="table bordered striped">
                            <thead>
                            <tr>
                                <th>1t Link</th>
                                <th>Links to</th>
                                <th>Visitors</th>
                                <th>Controls</th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php foreach ($this->user_links as $key => $row): ?>
                                <tr data-hash-id="<?= $row->link_hash_id ?>">
                                    <td>
                                        <div class="form-group">
                                            <input class="form-group-input copy-this shortened-link"
                                                   value="<?= $this->site_url . $row->link_hash_id ?>" readonly>
                                            <button class="form-group-btn copy-link tooltip" data-tooltip="Copy"><i
                                                        class="far fa-copy"></i></button>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <input class="form-group-input copy-this"
                                                   value="<?= base64_decode($row->url_base64) ?>" readonly>
                                            <button class="form-group-btn copy-link tooltip" data-tooltip="Copy"><i
                                                        class="far fa-copy"></i></button>
                                            <!-- <button class="form-group-btn tooltip" data-tooltip="Edit"><i class="far fa-edit"></i></button>-->
                                            <!-- TODO: add an edit button and required methods -->
                                        </div>
                                    </td>
                                    <td>
                                        <p><?= $row->visits ?></p>
                                        <!-- TODO: add UNIQUE visitor stats -->
                                    </td>
                                    <td>
                                        <div class="btn-container">
                                            <a href="#confirm-delete">
                                                <div class="btn btn-danger btn-small delete-link-btn">Delete</div>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="frame__footer"></div>
                </div>
            </div>
        </div>

    </div>
</section>


<div class="modal modal-animated--zoom-out" id="confirm-delete">
    <a href="#" class="modal-overlay close-btn" aria-label="Close"></a>
    <div class="modal-content" role="document">
        <div class="modal-header">
            <a href="#" class="u-pull-right" aria-label="Close"><span class="icon"><i
                            class="fa fa-wrapper fa-times"></i></span></a>
            <div class="modal-title">Confirm deletion</div>
        </div>
        <div class="modal-body">
            <!-- Modal content -->
            <div class="row">
                <h4><code id="link-to-be-deleted">- no link selected -</code></h4>
                <space></space>
                <h5>Are you sure you want to delete this link?</h5>
                <span class="text-danger">This action cannot be undone!</span>
                <space></space>
            </div>
            <div class="row">
                <div class="col">
                    <input type="hidden" name="api_key" id="api-key" value="<?= $this->user->api_key ?>">
                    <div class="btn btn-danger outline" id="confirm-delete-link-btn">Yes, Delete</div>
                </div>
                <div class="col">
                    <a href="#">
                        <div class="btn btn-dark outline">Cancel</div>
                    </a>
                </div>
            </div>
            <div class="row">
                <span class="text-danger" id="delete-error-message"></span>
            </div>
        </div>
    </div>
</div>


<div class="space large"></div>
