<div class="space large"></div>
<div class="space large"></div>

<section class="padtop">
    <div class="content">

        <div class="row title-row">
            <div class="col-12">
                <h1>My Account</h1>
            </div>
        </div>
        <div class="frame padded">
            <space class="large"></space>
            <div class="frame__body u-no-padding">
                <div class="row u-no-padding level fill-height">
                    <div class="col-6">
                        <form name="login-form" method="post" action="/accounts/login">
                            <div class="frame__body">
                                <h3>Login</h3>
                                <div class="form-section">
                                    <label for="email">Email</label>
                                    <div class="input-control">
                                        <input class="input-contains-icon" id="email" name="email" placeholder="Email"
                                               type="text" value="">
                                        <span class="icon">
                                                <i class="far fa-wrapper fa-envelope-open small"></i>
                                            </span>
                                    </div>
                                </div>
                                <div class="form-section">
                                    <label for="password">Password</label>
                                    <div class="input-control">
                                        <input class="input-contains-icon" id="password" name="password"
                                               placeholder="Password" type="password" value="">
                                        <span class="icon">
                                                <i class="fas fa-wrapper fa-key small"></i>
                                            </span>
                                    </div>
                                </div>
                                <space></space>
                                <button class="btn-info u-pull-right" name="btn" value="login" type="submit">Log In
                                </button>
                                <span class="fg-danger info"></span>
                            </div>
                        </form>
                    </div>
                    <div class="col-6">
                        <form name="register-form" method="post" action="/accounts/register">
                            <div class="padded">
                                <h3>Sign Up</h3>
                                <div class="form-section">
                                    <label for="register-email">Email</label>
                                    <div class="input-control">
                                        <input class="input-contains-icon" id="register-email" name="email"
                                               placeholder="Email" type="email" value="" required>
                                        <span class="icon">
                                                <i class="far fa-wrapper fa-envelope-open small"></i>
                                        </span></div>
                                </div>
                                <div class="form-section">
                                    <label for="register-username">Username</label>
                                    <div class="input-control">
                                        <input class="input-contains-icon" id="register-username" name="username" placeholder="Username"
                                               type="text" value="" required minlength="4">
                                        <span class="icon">
                                                <i class="far fa-wrapper fa-user-circle small"></i>
                                            </span>
                                    </div>
                                </div>
                                <div class="form-section">
                                    <label for="register-password">Password</label>
                                    <div class="input-control">
                                        <input class="input-contains-icon" id="register-password" name="password"
                                               placeholder="Password" type="password" value="" required minlength="6">
                                        <span class="icon">
                                                <i class="fas fa-wrapper fa-key small"></i>
                                        </span></div>
                                </div>
                                <button class="btn-info u-pull-right" name="btn" value="register" type="submit">Sign
                                    Up
                                </button>
                                <span class="fg-danger info"></span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <space class="large"></space>
        </div>


    </div>
</section>

<div class="space large"></div>