<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv=“Pragma” content=”no-cache”>
    <meta http-equiv=“Expires” content=”-1″>
    <meta http-equiv=“CACHE-CONTROL” content=”NO-CACHE”>
    <title>Fastest free link shortener - 1t.ie</title>
    <meta name="title" content="Fastest free link shortener - 1t.ie">
    <meta property="og:title" content="Fastest free link shortener - 1t.ie">
    <meta property="og:url" content="https://1t.ie/">
    <meta property="og:type" content="website">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--    <meta property="og:image" content="src/img/og_image.jpg">-->

    <link rel="stylesheet" href="https://unpkg.com/cirrus-ui@0.5.5/dist/cirrus.min.css">
    <link rel="stylesheet" href="<?= $this->assets ?>css/style.css?<?= $this->version ?>">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <link rel="apple-touch-icon" sizes="57x57" href="<?= $this->assets ?>img/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="<?= $this->assets ?>img/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="<?= $this->assets ?>img/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="<?= $this->assets ?>img/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="<?= $this->assets ?>img/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="<?= $this->assets ?>img/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="<?= $this->assets ?>img/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="<?= $this->assets ?>img/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="<?= $this->assets ?>img/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="<?= $this->assets ?>img/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?= $this->assets ?>img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="<?= $this->assets ?>img/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="<?= $this->assets ?>img/favicon-16x16.png">
    <link rel="manifest" href="<?= $this->assets ?>manifest.json">
    <meta name="msapplication-TileImage" content="<?= $this->assets ?>img/ms-icon-144x144.png">
    <meta name="msapplication-TileColor" content="#ff2960">
    <meta name="theme-color" content="#000">
</head>
