<body>

<div id="header" class="header header-fill unselectable header-fixed no-transition header-dark header-animated">
        <div class="header-brand">
            <div class="nav-item">
                <a href="/">
                    <h6 class="title">1t.ie</h6>
                </a>
            </div>
            <div class="nav-item nav-btn" id="header-btn">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div class="header-nav" id="header-menu">
            <div class="nav-left u-text-center">
                <div class="nav-item u-text-center">
                    <a href="https://github.com/xy3/1t.ie">
                    <span class="icon">
                    <i class="fab fa-wrapper fa-github"></i>
                    </span>
                    </a>
                </div>
            </div>
            <div class="nav-right u-text-center nav-menu">
                <div class="nav-item">
                    <a href="/">
                        <span class="icon">
                            <i class="fas fa-wrapper fa-home small"></i>
                        </span>
                        Home
                    </a>
                </div>
                <div class="nav-item">
                    <a href="/links">
                        <span class="icon">
                            <i class="fas fa-wrapper fa-link small"></i>
                        </span>
                        My Links
                    </a>
                </div>
                <!-- TODO: My account is a work in progress -->
<!--                <div class="nav-item">-->
<!--                    <a href="/user">-->
<!--                        <span class="icon">-->
<!--                            <i class="fas fa-wrapper fa-cog small"></i>-->
<!--                        </span>-->
<!--                        My Account-->
<!--                    </a>-->
<!--                </div>-->
                <?php if ($this->logged_in): ?>
                <div class="nav-item">
                    <a href="/accounts/logout" id="logout-btn">
                        <span class="icon">
                            <i class="fas fa-wrapper fa-sign-out-alt small"></i>
                        </span>
                        Logout
                    </a>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>